ASCEND_RT_VISIBLE_DEVICES=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15 \
CURRENT_IP=80.48.5.52  MASTER_ADDR=80.48.5.88  NNODES=2  NPUS_PER_NODE=16  SOCKET_IFNAME=ens1f3 \
RESOURCE_LAYOUT=/workspace/vime/scripts/resource_layout.dual88train52infer.yaml \
MAX_TOKENS_PER_GPU=32768 \
VIME_MEM_PROBE=1 \
FEAT_TRAIN_EXPANDABLE=1 \
VIME_EMPTY_CACHE_PER_STEP=1 \
ROLLOUT_BATCH_SIZE=2  N_SAMPLES_PER_PROMPT=2  GLOBAL_BATCH_SIZE=4  NUM_ROLLOUT=200 \
FEAT_DP_EXTERNAL_LB=0 FEAT_BALANCE_SCHED=0 FEAT_LB_PROXY=1 FEAT_CROSS_DP_EP=0 \
FEAT_ROLLOUT_EP=0 FEAT_FLASHCOMM1=0 FEAT_PREFIX_CACHE=1 FEAT_MULTISTREAM_SHARED_EXPERT=1 FEAT_STATIC_KERNEL=1 FEAT_HCCL_AIV=1 \
bash scripts/run-qwen36-35b-polar-minimal.sh
# ── 备选:跨 DP EP(DP+EP 同开)。冒烟通过 external-LB+Balance 后,把上面 FEAT_CROSS_DP_EP=0 改成 1 即可(其余不动;EP world=dp×tp=16,experts/card=256/16=16)。整行等价形式如下: ──
# FEAT_DP_EXTERNAL_LB=1 FEAT_BALANCE_SCHED=1 FEAT_LB_PROXY=1 FEAT_CROSS_DP_EP=1 FEAT_ROLLOUT_EP=0 FEAT_FLASHCOMM1=0 FEAT_PREFIX_CACHE=1 FEAT_MULTISTREAM_SHARED_EXPERT=1 FEAT_STATIC_KERNEL=1 FEAT_HCCL_AIV=1 bash scripts/run-qwen36-35b-polar-minimal.sh
